apiVersion: v2
name: hyperflow-storage
description: Storage deployment for Hyperflow
type: application
version: 0.1.0
appVersion: 1.5.4
dependencies:
  - name: rook-ceph
    version: 1.5.4
    repository: https://charts.rook.io/release
