apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workflow.pvc.name }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.workflow.pvc.storage }}
  storageClassName: {{ .Values.workflow.pvc.storageClass }}
