{{- $rookCeph := index .Values "rook-ceph" -}}
{{- if $rookCeph.csi.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  {{- if $rookCeph.csi.serviceMonitor.namespace }}
  namespace: {{ $rookCeph.csi.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if $rookCeph.csi.serviceMonitorselector }}
    {{- toYaml $rookCeph.csi.serviceMonitor.selector | nindent 4 }}
    {{- end }}
    {{- if $rookCeph.csi.serviceMonitor.additionalLabels }}
    {{- toYaml $rookCeph.csi.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: csi-metrics
  endpoints:
    - port: csi-http-metrics
      path: /metrics
      interval: 5s
  {{- if $rookCeph.csi.enableGrpcMetrics }}
    - port: csi-grpc-metrics
      path: /metrics
      interval: 5s
  {{- end }}
{{- end -}}
