{{- if .Values.ceph.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.ceph.storageclass.name }}
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  # clusterID is the namespace where operator is deployed.
  clusterID: {{ .Release.Namespace }}
  # CephFS filesystem name into which the volume shall be created
  fsName: {{ .Values.ceph.filesystem.name }}

  {{- if .Values.ceph.storageclass.pool }}
  pool: {{ .Values.ceph.storageclass.pool }}
  {{- end }}

  {{- if .Values.ceph.storageclass.rootPath }}
  rootPath: {{ .Values.ceph.storageclass.rootPath }}
  {{- end }}

  # The secrets contain Ceph admin credentials. These are generated automatically by the operator
  # in the same namespace as the cluster.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}

  {{- if .Values.ceph.storageclass.mounter }}
  mounter: {{ .Values.ceph.storageclass.mounter }}
  {{- end }}
reclaimPolicy: {{ .Values.ceph.storageclass.reclaimPolicy }}
allowVolumeExpansion: {{ .Values.ceph.storageclass.allowVolumeExpansion }}
{{- end -}}
